### ISSUE TITLE
Something broken with rhel6 pip

### ISSUE THREAD

**Issue by kdelee** [quipucords/ci#73]
Our RHEL 6 install jobs are failing because of some bug in pip.

We are supposed to be using a python 2.6 virtual environment but this is happening when you try and use pip:

```
+ pip install -U pip
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/cc962f28/virtualenvs/d41d8cd9/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/home/jenkins/shiningpanda/jobs/cc962f28/virtualenvs/d41d8cd9/lib/python2.6/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/home/jenkins/shiningpanda/jobs/cc962f28/virtualenvs/d41d8cd9/lib/python2.6/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/home/jenkins/shiningpanda/jobs/cc962f28/virtualenvs/d41d8cd9/lib/python2.6/site-packages/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
```

Looks like a dict comprehension is being used but that did not land until python 2.7 I think from reading this PEP: https://www.python.org/dev/peps/pep-0274/

**Comment by kdelee** [comment]
Checked to see and it is for sure using the virtualenvironment pip :cry: 
```
+ python --version
Python 2.6.6
+ which python
/home/jenkins/shiningpanda/jobs/3673c3dc/virtualenvs/d41d8cd9/bin/python
+ which pip
/home/jenkins/shiningpanda/jobs/3673c3dc/virtualenvs/d41d8cd9/bin/pip
```

Maybe will try not using virtual environment.
